Library/Library/Models/AddBooksViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DBLib.Models;
using System.Web;

namespace Library.Models
{
    /// <summary>
    /// Reflects book from View for further saving in DB
    /// </summary>
    public class AddBooksViewModels
    {
        [Required(ErrorMessage = "Необхідне поле")]
        [Display(Name = "Заголовок")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Необхідне поле")]
        [Range(1900, 3000, ErrorMessage = "Рік не може бути меншим за {1}")]
        [Display(Name = "Рік видання")]
        public short Year { get; set; }

        [Display(Name = "Читання в бібліотеці")]
        [UIHint("Boolean")]
        public bool LibraryReading { get; set; }

        [Required(ErrorMessage = "Необхідне поле")]
        [Display(Name = "Кількість книг")]
        [Range(0, int.MaxValue, ErrorMessage = "{0} не може бути менша за {1}")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "Необхідне поле")]
        [Display(Name = "Сторінок")]
        [Range(1, int.MaxValue, ErrorMessage = "{0} не може бути менше за {1}")]
        public int Pages { get; set; }

        [Required(ErrorMessage = "Необхідне поле")]
        [Display(Name = "Код ISBN")]
        public string ISBN { get; set; }

        [Required(ErrorMessage = "А де ж назва розділу?")]
        [Display(Name = "Назва розділу")]
        public string SectionName { get; set; }

        [Required(ErrorMessage = "Як же без видавця")]
        [Display(Name = "Видавець")]
        public string PublisherName { get; set; }

        [Required(ErrorMessage = "Хоча б один автор має бути")]
        [Display(Name = "Автори")]
        public virtual ICollection<Guid> AuthorsId { get; set; }

        [Display(Name = "Обкладинка")]
        public HttpPostedFileBase TitlePic { get; set; }
    }
}

Library/Library/Controllers/LibraryManageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DBLib.Models;
using Library.Models;
using DBLib;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Library.Controllers
{
    /// <summary>
    /// Contains controllers, that process requests
    /// for librarians/admins
    /// </summary>
    [CheckingIfBanned]
    [Authorize(Roles = "librarian")]
    public class LibraryManageController : Controller
    {
        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult AddBook()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult AddBook(AddBooksViewModels bookViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var book = new Book(bookViewModel.ISBN, bookViewModel.Title, bookViewModel.LibraryReading, bookViewModel.Pages,
                           bookViewModel.Quantity, bookViewModel.Year);

                    //Adding book picture
                    if (bookViewModel.TitlePic != null)
                    {
                        bool picSaved = PictureOperations.SaveTitlePic(bookViewModel.TitlePic, book.Id, Server.MapPath("~/TitlePic/"));

                        if (picSaved == false)
                        {
                            throw new ExceptionExt("Файл обкладинки не вдалося додати");
                        }
                    }

                    DBLib.DBCommands.AddBook(book, bookViewModel.AuthorsId, bookViewModel.PublisherName, bookViewModel.SectionName);
                }
                catch (ExceptionExt ex)
                {
                    return RedirectToAction("ErrorExt", "Error", new ExceptionExt("Помилка додавання книги", ex.ToString(), MessageState.Error));
                }
            }
            else
            {
                return View();
            }
            return RedirectToAction("ErrorExt", "Error", new ExceptionExt("Книгу додано", null, MessageState.Succes));
        }

        public JsonResult GetAuthorsJson()
        {
            var authors = DBCommands.GetAllAuthors();
            var authorsNameAndId = authors.Select(a => new { Id = a.Id, Name = a.Name });
            return new JsonResult { Data = authorsNameAndId, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public JsonResult AddAuthorToDB(string authorName)
        {
            if (authorName.Length > 3)
            {
                string result = DBLib.DBCommands.AddAuthor(authorName);

                return new JsonResult() { Data = result };
            }
            else
            {
                return new JsonResult() { Data = "Закоротке ім'я" };
            }
        }

        public JsonResult GetPublishersJson()
        {
            var publishers = DBCommands.GetAllPublishers();
            var publishersNameAndId = publishers.Select(a => a.Name);
            return new JsonResult { Data = publishersNameAndId, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult GetSectionsJson()
        {
            var sections = DBCommands.GetAllSections();
            var sectionsNameAndId = sections.Select(a => a.Name);
            return new JsonResult { Data = sectionsNameAndId, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult AddPublisher()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult AddPublisher(Publisher publisher)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    DBCommands.AddPublisher(publisher);
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                var exExt = new ExceptionExt(ex);
                return RedirectToAction("ErrorExt", "Error", exExt);
            }

            return RedirectToAction("ErrorExt", "Error", new ExceptionExt("Видання успішно додано", null, MessageState.Succes));
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult AddAuthor()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult AddAuthor(Author author)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    DBCommands.AddAuthor(author.Name);
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                var exExt = new ExceptionExt(ex);
                return RedirectToAction("ErrorExt", "Error", exExt);
            }

            return RedirectToAction("ErrorExt", "Error", new ExceptionExt("Автора успішно додано", null, MessageState.Succes));
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult AddSection()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult AddSection(Section section)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    DBCommands.AddSection(section);
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                var exExt = new ExceptionExt(ex);
                return RedirectToAction("ErrorExt", "Error", exExt);
            }

            return RedirectToAction("ErrorExt", "Error", new ExceptionExt("Розділ успішно додано", null, MessageState.Succes));
        }

        public ActionResult RegisteredUsers()
        {
            var registeredUsers = DBCommands.GetOnlyRegisteredUsers();

            return View(registeredUsers);
        }

        public ActionResult ShowUserInfo(string id)
        {
            var usersInfo = DBCommands.GetUserById(id);
            if(usersInfo == null)
            {
                return RedirectToAction("ErrorExt", "Error", new ExceptionExt("Користувач не знайдений", "Немає користувача з таким Id, або Id не вказаний", MessageState.Error));
            }

            ViewBag.usersInfo = usersInfo; 

            DBCommands.RemoveOldUserOrders(id);
            List<BooksRenting> allBooksRentings = DBCommands.GetUserOrderedBooks(id);

            List<BooksRenting> booksOrdered = allBooksRentings.Where(br => br.TakingDate == null).ToList();

            List<BooksRenting> booksTaked = allBooksRentings.Where(br => br.ReturningDate == null
                && br.TakingDate != null).ToList();

            ViewBag.booksOrdered = booksOrdered;
            ViewBag.booksTaked = booksTaked;

            return View(allBooksRentings);
        }

        [HttpPost]
        public ActionResult UserTakingBook(string orderForTakingId, string userId)
        {
            DBCommands.TakeBook(orderForTakingId);

            return RedirectToAction("ShowUserInfo", new { id = userId });
        }

        [HttpPost]
        public ActionResult UserReturningBook(string orderForReturningId, string userId)
        {
            DBCommands.ReturnBook(orderForReturningId);

            return RedirectToAction("ShowUserInfo", new { id = userId });
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult EditBook(Guid? id)
        {
            if(id == null)
            {
                return RedirectToAction("ErrorExt", "Error", new ExceptionExt("Id книги не вказано", null, MessageState.Error));
            }

            var book = DBCommands.GetBookWithAdditionalInfoById((Guid)id);
            ViewBag.Publishers = DBCommands.GetAllPublishers();
            ViewBag.Sections = DBCommands.GetAllSections();
            ViewBag.Authors = DBCommands.GetAllAuthors();

            if (book == null)
            {
                return RedirectToAction("ErrorExt", "Error", new ExceptionExt("Книгу не знайдено", null, MessageState.Error));
            }

            return View(book);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult EditBook(Book book, Guid Section, Guid Publisher, Guid[] Authors, HttpPostedFileBase TitlePic)
        {
            try
            {
                if(book != null && Section != null && Publisher != null && Authors != null)
                {
                    DBCommands.EditBook(book, Section, Publisher, Authors);

                    if (TitlePic != null)
                    {
                        bool picSaved = PictureOperations.SaveTitlePic(TitlePic, book.Id, Server.MapPath("~/TitlePic/"));

                        if (picSaved == false)
                        {
                            throw new ExceptionExt("Файл обкладинки не вдалося додати");
                        }
                    }

                    return RedirectToAction("ErrorExt", "Error", new ExceptionExt("Успішо відредаговано", null, MessageState.Succes));
                }
                else
                {
                    return RedirectToAction("ErrorExt", "Error", new ExceptionExt("Не всі дані були вказані", null, MessageState.Error));
                }
            }
            catch (Exception ex)
            {
                var exExt = new ExceptionExt(ex);
                return RedirectToAction("ErrorExt", "Error", exExt);
            }
        }

        [HttpPost]
        public ActionResult DeleteBook(Guid bookId)
        {
            DBCommands.DeleteBook(bookId);

Library/Library/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Library/Library/Views/Home/AddBook.cshtml
@{
    ViewBag.Title = "AddBook";
    @model Library.Models.AddBooksViewModels
}

<h2>AddBook</h2>
<div class="panel panel-info">
    <div class="panel-heading text-uppercase">Додати книгу</div>
    <div class="panel-body">
        <form method="post" action="/Home/AddBook" role="form" enctype="multipart/form-data">
            <div>
                @Html.LabelFor(m => m.AuthorsId)
                <input type="text" oninput="getAuthorsByNameTerm()" id="authorSearch" />
                <select hidden id="authorSelect" class="authorSelect"></select>
                @Html.ValidationMessageFor(m => m.AuthorsId)
                <div id="selectAuthorBnt" disabled class="btn btn-default btn-xs" onclick="selectAuthor()">Обрати автора</div>
                <div id="addAuthorBnt" class="btn btn-default btn-xs" onclick="addAuthorToDB()">Зберегти нового автора</div>
                <div id="selectedAuthorsDisplay"></div>
            </div>
            <div>
                @Html.LabelFor(m => m.ISBN)
                @Html.TextBoxFor(m => m.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.ISBN)
            </div>
            <div>
                @Html.LabelFor(m => m.LibraryReading)
                <input type="checkbox" value="true" name="LibraryReading" />
                @Html.ValidationMessageFor(m => m.LibraryReading)
            </div>
            <div>
                @Html.LabelFor(m => m.Pages)
                @Html.TextBoxFor(m => m.Pages, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.Pages)
            </div>
            <div>
                @Html.LabelFor(m => m.PublisherName)
                <input name="PublisherName" id="PublisherName" list="publisherList" />
                @Html.ActionLink("Додати видавця", "AddPublisher", "LibraryManage", null, new {@class="btn btn-default btn-xs"})
                <div class="btn btn-default btn-xs" onclick="updatePublishersList()">Оновити</div>
                @Html.ValidationMessageFor(m => m.PublisherName)
            </div>
            <div>
                @Html.LabelFor(m => m.Quantity)
                @Html.TextBoxFor(m => m.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.Quantity)
            </div>
            <div>
                @Html.LabelFor(m => m.SectionName)
                <input name="SectionName" id="SectionName" list="sectionList" />
                @Html.ActionLink("Додати розділ", "AddSection", "LibraryManage", null, new { @class = "btn btn-default btn-xs" })
                <div class="btn btn-default btn-xs" onclick="updateSectionsList()">Оновити</div>
                @Html.ValidationMessageFor(m => m.SectionName)
            </div>
            <div>
                @Html.LabelFor(m => m.Title)
                @Html.TextBoxFor(m => m.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.Title)
            </div>
            <div>
                @Html.LabelFor(m => m.Year)
                @Html.TextBoxFor(m => m.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.Year)
            </div>
            <div>
                @Html.LabelFor(m => m.TitlePic)
                <input type="file" name="TitlePic" id="TitlePic"  accept=".jpg"/>
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Додати книгу</button>
        </form>
    </div>
</div>

<datalist id="publisherList">
</datalist>
<datalist id="sectionList">
</datalist>

@section scripts{
    <script src="~/Scripts/myScripts.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/jquery-ui-git.css">

    <script>
        var authorsArray = getAllAuthors();
        updatePublishersList();
        updateSectionsList();

        function getAllAuthors() {
            $.ajax({
                url: '@Url.Action("GetAuthorsJson")',
                //type: 'POST',
                dataType: "json",
                success: function (data)
                {
                    authorsArray = data;
                },
                error: function(xhr, status, error){
                    alert("Error");
                }
             });
        }

        function selectToggle(state) {
            if (state == "off") {
                $("#authorSelect").hide();
                $("#selectAuthorBnt").attr('disabled', 'disabled');
            }
            else {
                $("#authorSelect").show();
                $("#selectAuthorBnt").removeAttr('disabled');
            }

        }

        function getAuthorsByNameTerm() {
            var authorNameTerm = $("#authorSearch").val();

            var authorsFind = authorsArray.filter(function (element) {
                if (element.Name.toLowerCase().includes(authorNameTerm.toLowerCase()))
                    return true;
                return false;
            });

            $("#authorSelect").empty();

            if (authorsFind.length == 0) {
                selectToggle('off')
                return 0;
            }

            selectToggle('on');

            authorsFind.map(function (author) {
                $('<option type="text" readonly value="'
                    + author.Id + '">' + author.Name + '</option>').appendTo("#authorSelect");
            });
        }

        function selectAuthor(Id, Name) {
            var authorId = (Id != undefined) ? Id : $("#authorSelect option:selected").val();
            var authorName = (Name != undefined) ? Name : $("#authorSelect option:selected").text();
            if (authorId != undefined) {
                $('<div class="selectedBox" id="' + authorId + '"><input hidden type="checkbox"checked name="AuthorsId" value="'
                    + authorId + '">' + authorName + ' <span class="removeBtn" onclick="removeEl(\'#'
                    + authorId + '\')">X</span></div>').appendTo("#selectedAuthorsDisplay");
                $('#authorSearch').val('');
                $("#authorSelect").empty();
                selectToggle('off');
            }
        }

        function addAuthorToDB() {
            var authorName = $('#authorSearch').val().trim();
            $.ajax({
                url: '@Url.Action("AddAuthorToDB")',
                type: 'POST',
                data: { authorName: authorName },
                success: function (Id) {
                    switch (Id) {
                        case "-1": alert("Помилка додавання автора в БД"); break;
                        case "0": alert("Цей автор вже є в БД"); break;
                        case "Закоротке ім'я": alert("Закоротке ім'я"); break;
                        default: alert("Автор успішно доданий"); selectAuthor(Id, authorName); break;
                    }
                },
                error: function () {
                    alert('Помилка при додаванні');
                }
            });
        }

        function removeEl(selector) {
            $(selector).remove();
        }
        
        function updatePublishersList() {
            $("#publisherList").empty();
            
            $.ajax({
                url: '@Url.Action("GetPublishersJson")',
                dataType: "json",
                success: function (data)
                {
                    data.map(function (publisherName) {
                        $('<option>' + publisherName + '</option>').appendTo("#publisherList");
                    }
                    )
                },
                error: function(xhr, status, error){
                    alert("Error");
                }
             });
        }

        function updateSectionsList(){
            $("#sectionList").empty();
            
            $.ajax({
                url: '@Url.Action("GetSectionsJson")',
                dataType: "json",
                success: function (data)
                {
                    data.map(function (publisherName) {
                        $('<option>' + publisherName + '</option>').appendTo("#sectionList");
                    }
                    )
                },
                error: function(xhr, status, error){
                    alert("Error");
                }
             });
        }

    </script>
}

Library/Library/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Library/Library/Views/Home/Search.cshtml
@{
    ViewBag.Title = "Пошук";
}

<h2>Пошук</h2>

@if (ViewBag.findedAuthors.Count > 0)
{
<h5 class="alertInfo bg-success text-primary">Знайдено <span class="badge">@ViewBag.findedAuthors.Count</span> авторів за цим запитом</h5>
    <ul>
        @foreach (var author in ViewBag.findedAuthors)
        {
            <li><a href="@Url.Action("ShowAuthor","Home",new { id = author.Id})">@author.Name</a></li>
        }
    </ul>
}
else
{
    <h5 class="alertInfo bg-warning text-primary">Авторів за цим запитом не знайдено...</h5>
}

@if (ViewBag.findedBooks.Count > 0)
{
    <h5 class="alertInfo bg-success text-primary">Знайдено <span class="badge">@ViewBag.findedBooks.Count</span> книг за цим запитом</h5>
    <ul>
        @foreach (var book in ViewBag.findedBooks)
        {
            <li><a href="@Url.Action("ShowBook","Home",new { id = book.Id})">@book.Title</a></li>
        }
    </ul>
}
else
{
    <h5 class="alertInfo bg-warning text-primary">Книг за цим запитом не знайдено...</h5>
}

Library/Library/Views/Home/ShowAuthor.cshtml
@if (Model != null)
{
    ViewBag.Title = "Автор: " + Model.Name;
    @model DBLib.Models.Author

    <h2>
        Автор: @Model.Name
        @if (User.IsInRole("admin"))
        {
            <span id="editFormShowBtn" class="btn btn-warning btn-xs glyphicon glyphicon-pencil"></span>
        }
    </h2>

    if (User.IsInRole("admin"))
    {
    <div id="editForm" class="hidden">
        <input hidden id="IdInput" size="50" value="@Model.Id" />
        <input id="newNameInput" size="50" value="@Model.Name" />
        <button id="saveChangesBtn" class="btn btn-success btn-sm">Зберегти зміни</button>
    </div>
    }

    if (Model.Books.Count > 0)
    {
        <h5 class="alertInfo bg-success text-primary">Цей автор має <span class="badge">@Model.Books.Count</span> книг</h5>
        @*<ul>
            @foreach (var book in Model.Books)
            {
                <li><a href="@Url.Action("ShowBook", "Home", new { id = book.Id })">@book.Title</a></li>
            }
        </ul>*@
        
        @Html.Partial("_BooksView", Model.Books)
    }
    else
    {
        <h5 class="alertInfo bg-warning text-primary">Цей автор не має книг</h5>
        <span>Можете переглянути інших авторів</span>
        <ul>
            @foreach (var author in ViewBag.OtherAuthors)
            {
                <li><a href="@Url.Action("ShowAuthor", "Home", new { id = author.Id })">@author.Name</a></li>
            }
        </ul>
    }
}
else
{
    ViewBag.Title = "Автори";
    <h2>Автори</h2>
    <h4 class="alertInfo bg-success text-primary">До вашої уваги такі автори:</h4>

    <ul>
        @foreach (var author in ViewBag.OtherAuthors)
        {
            <li><a href="@Url.Action("ShowAuthor", "Home", new { id = author.Id })">@author.Name</a></li>
        }
    </ul>
}

@if (User.IsInRole("admin"))
{
@section scripts
{
    <script>
        function toggleEditForm() {
            $("#editForm").toggleClass("hidden");
        }

        function saveChanges() {
            var newName = $("#newNameInput").val();
            var Id = $("#IdInput").val();
            if (newName.length > 1)
            {
                $.ajax({
                    url: '@Url.Action("EditAuthor", "LibraryManage")',
                    type: 'POST',
                    data: { Id: Id, Name: newName },
                    success: () => {
                        alert("Успішно змінено");
                        toggleEditForm();
                        toggleBlockUserBtns();
                    },
                    error: function () {
                        alert('Помилка при зміні');
                    }
                });
            }
            else {
                alert("Закоротка назва");
            }
        }

            $("#editFormShowBtn").click(toggleEditForm);
            $("#saveChangesBtn").click(saveChanges);
    </script>
}
}

Library/Library/Views/Home/ShowBook.cshtml
@{
    @model DBLib.Models.Book
    ViewBag.Title = @Model.Title;
}

<h1>@Model.Title</h1>
<h4 title="Кількість прочитань">
    <span class="label label-default"><span class="glyphicon glyphicon-lamp"> @ViewBag.BookRating</span></span>
    @if (User.IsInRole("librarian"))
    {
        <span class="btn btn-default btn-sm">Додано: @Model.AddingDate</span>
    }
</h4>
<hr />

@if (Model.Deleted)
{
    <h3 class="alertInfo bg-danger text-primary"><strong>КНИГУ ВИДАЛЕНО!</strong></h3>
}
<div class="container-fluid @(Model.Deleted ? "bg-danger": "")">
    <div class="row">
        <div class="col-sm-6 col-md-8 col-lg-6 biggerText">
            <div>
                @Html.LabelFor(b => b.ISBN)
                @Html.DisplayFor(b => b.ISBN)
            </div>
            <div>
                @Html.LabelFor(b => b.Pages)
                @Html.DisplayFor(b => b.Pages)
            </div>
            <div>
                @Html.LabelFor(b => b.Quantity)
                @Model.Quantity <span class="text-success">(@ViewBag.freeBookCount)</span>
            </div>
            <div>
                @Html.LabelFor(b => b.Year)
                @Html.DisplayFor(b => b.Year)
            </div>
            @if (Model.LibraryReading)
            {
                <div class="btn btn-warning btn-sm">
                    Доступна для читання лише в бібліотеці!
                </div>
            }
            else
            {
                <div class="btn btn-success btn-sm">
                    Доступна для читання вдома
                </div>
            }
            <div>
                @Html.LabelFor(b => b.Publisher.Name)
                <a href="@Url.Action("ShowPublisher", "Home", new { id = Model.Publisher.Id })">@Model.Publisher.Name</a>
            </div>
            <div>
                @Html.LabelFor(b => b.Section.Name)
                <a href="@Url.Action("ShowSection", "Home", new { id = Model.Section.Id })">@Model.Section.Name</a>
            </div>
            <div>
                @Html.LabelFor(b => b.Authors)
                <ul>
                    @foreach (var author in Model.Authors)
                    {
                        <li><a href="@Url.Action("ShowAuthor", "Home", new { id = author.Id })">@author.Name</a></li>
                    }
                </ul>
            </div>
            @if (ViewBag.userExist && !User.IsInRole("librarian"))
            {
                if (ViewBag.userOrderedTheBook) //Book is ordered by this user
                {
                    <div id="addBookOrder" class="btn btn-primary hidden">Замовити</div>
                    <div id="cancelBookOrder" class="btn btn-danger">Відмінити</div>
                }
                else
                {
                    //User don`t has penalty, he can order book
                    if (!ViewBag.userHasPenalty)
                    {
                        if (ViewBag.userTakeTheBook)
                        {
                            <div class="btn btn-warning">Ця книга вже у вас на руках</div>
                        }
                        //If the book is free (at least one)
                        else if (@ViewBag.freeBookCount > 0)
                        {
                            <div id="addBookOrder" class="btn btn-primary">Замовити</div>
                            <div id="cancelBookOrder" class="btn btn-danger hidden">Відмінити</div>
                        }
                        else
                        {
                            <div class="btn btn-default">Вільних книг немає</div>
                        }
                    }
                    else
                    {
                        <a href="@Url.Action("MyBooks")"><div class="btn btn-danger">Ви маєте заборгованість!</div></a>
                    }
                }
                <div class="text-muted text-center info"><span class="glyphicon glyphicon-info-sign"></span> Увага, замовлення буде дійсне протягом 24 годин</div>
            }
            else if (User.IsInRole("admin"))
            {
                @Html.ActionLink("Редагувати книгу", "EditBook", "LibraryManage", new { id = Model.Id }, new { @class = "btn btn-warning" });
            }
            else if (!ViewBag.userExist)
            {
                @Html.ActionLink("Щоб замовити книгу, необхідно увійти", "Login", "Account", null, new { @class = "btn btn-default" });
            }
        </div>
        <div class="col-sm-6 col-md-4 col-lg-6">
            <img class="bookTitleImgLg" src="~/TitlePic/@{@Model.Id;}.jpg" onerror="imgError(this)" />
        </div>
    </div>
</div>
@Html.Partial("_Comments", (List<DBLib.Models.Comment>)ViewBag.Comments)

@section scripts{
    <script>
        $("#addBookOrder").click(addBookOrder);
        $("#cancelBookOrder").click(cancelBookOrder);

        function toggleOrderBtn() {
            $("#addBookOrder").toggleClass("hidden");
            $("#cancelBookOrder").toggleClass("hidden");
        }

        function addBookOrder() {
            $.ajax({
                url: '@Url.Action("BookOrder")',
                data: { BookId: '@Model.Id', UserId: '@ViewBag.userId' },
                type: 'POST',
                dataType: "json",
                success: function (data)
                {
                    toggleOrderBtn();
                    if (data != "success")
                        alert(data);
                },
                error: function(xhr, status, error){
                    alert("Помилка :(");
                }
             });
        }

        function cancelBookOrder() {
            $.ajax({
                url: '@Url.Action("CancelBookOrder")',
                data: { BookId: '@Model.Id', UserId: '@ViewBag.userId' },
                type: 'POST',
                dataType: "json",
                success: function (data)
                {
                    toggleOrderBtn();
                    if (data != "success")
                        alert(data);
                },
                error: function(xhr, status, error){
                    alert("Помилка :(");
                }
             });
        }
    </script>
}